version: "3.8"

services:
  mongo:
    image: mongo
    container_name: github-analyzer-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: dhruvgajera/github-analyzer
    env_file: .env
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://mongo:27017/GitHub-Analyzer

volumes:
  mongo_data:
